{
 "title": "Nginx Test dashboard",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Total Requests",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "log_type",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "log_type:nginx",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "HTTP Methods",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "method",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "20" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "log_type:nginx",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "All Status Codes",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "status_code_2",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "20" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "log_type:nginx",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Clients Requests Ips",
   "type": "barchart",
   "description": "for host ip-172-31-15-76",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "client_ip",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "host:ip-172-31-15-76",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Top User Agents",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "uniqueValues" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "user_agent",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "20" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "log_type:nginx",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Top Paths",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "url",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "20" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "log_type:nginx",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "404 Not Found",
   "type": "barchart",
   "description": "404 for nginx logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "url",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "20" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "status_code_2:404",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Malicious Requests (MISP DB)",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "misp_Event.id",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "20" },
       "type": "terms"
      },
      {
       "field": "client_ip_2",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "20" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "log_type:nginx",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Threat Intel (ALL Req)",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "client_ip_2",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "20" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "log_type:nginx",
     "timeField": "timestamp"
    }
   ]
  }
 ]
}